In [4]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [6]:
np.random.seed(42)

num_users = 500

users = pd.DataFrame({
    "user_id": range(1, num_users + 1),
    "age": np.random.randint(18, 60, num_users),
    "gender": np.random.choice(["Male", "Female"], num_users),
    "location": np.random.choice(
        ["India", "USA", "UK", "Germany", "Canada"], num_users
    )
})

users

     user_id  age  gender location
0          1   56    Male  Germany
1          2   46  Female    India
2          3   32    Male  Germany
3          4   25    Male      USA
4          5   38    Male       UK
..       ...  ...     ...      ...
495      496   56  Female   Canada
496      497   49  Female      USA
497      498   41    Male  Germany
498      499   40    Male      USA
499      500   49    Male       UK

[500 rows x 4 columns]

In [8]:
users.to_csv("users.csv", index=False)

In [10]:
num_products = 300

products = pd.DataFrame({
    "product_id": range(1, num_products + 1),
    "category": np.random.choice(
        ["Electronics", "Fashion", "Home", "Books", "Beauty"], num_products
    ),
    "price": np.random.randint(200, 5000, num_products),
    "profit_margin": np.round(np.random.uniform(0.05, 0.4, num_products), 2),
    "inventory_level": np.random.randint(10, 500, num_products)
})

products

     product_id     category  price  profit_margin  inventory_level
0             1      Fashion   1135           0.38               58
1             2      Fashion   4537           0.17              301
2             3         Home    201           0.09              391
3             4       Beauty   3048           0.22              333
4             5       Beauty   4244           0.14               87
..          ...          ...    ...            ...              ...
295         296  Electronics   3388           0.15              435
296         297        Books    914           0.32               44
297         298        Books   4346           0.27              311
298         299  Electronics   4054           0.18              419
299         300      Fashion   4619           0.12               78

[300 rows x 5 columns]

In [12]:
products.to_csv("products.csv", index=False)

In [14]:
num_interactions = 20000

interaction_types = ["click", "add_to_cart", "purchase"]

interactions = pd.DataFrame({
    "user_id": np.random.choice(users["user_id"], num_interactions),
    "product_id": np.random.choice(products["product_id"], num_interactions),
    "event_type": np.random.choice(
        interaction_types,
        num_interactions,
        p=[0.6, 0.25, 0.15]
    ),
    "timestamp": [
        datetime.now() - timedelta(days=np.random.randint(0, 180))
        for _ in range(num_interactions)
    ]
})

interactions

       user_id  product_id   event_type                  timestamp
0          349          73  add_to_cart 2025-09-08 17:25:19.936687
1          320          10  add_to_cart 2025-07-13 17:25:19.936687
2          421          61        click 2025-07-21 17:25:19.936687
3          468          50  add_to_cart 2025-06-30 17:25:19.936687
4           49         122        click 2025-12-12 17:25:19.936687
...        ...         ...          ...                        ...
19995      442         136        click 2025-10-22 17:25:20.069369
19996        3         175  add_to_cart 2025-07-13 17:25:20.069369
19997      307         126     purchase 2025-07-18 17:25:20.069369
19998      243         171        click 2025-11-16 17:25:20.069369
19999       56         266     purchase 2025-09-11 17:25:20.069369

[20000 rows x 4 columns]

In [16]:
interactions.to_csv("interactions.csv", index=False)